# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import protos.models_pb2 as models__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmaster.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cmodels.proto\"P\n\x0fPipelineRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x31\n\rcreation_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x12\n\x10PipelineResponse\"?\n\x14RegisterAgentRequest\x12\'\n\x0bsystem_info\x18\x01 \x01(\x0b\x32\x12.protos.SystemInfo\"*\n\x15RegisterAgentResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\"Z\n\x15\x41gentHeartBeatRequest\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x11\n\tpid_count\x18\x02 \x01(\x05\x12\x1b\n\x13percent_memory_used\x18\x03 \x01(\x02\"\x18\n\x16\x41gentHeartBeatResponse2\xf4\x01\n\x06Master\x12\x46\n\x0f\x45xecutePipeline\x12\x17.protos.PipelineRequest\x1a\x18.protos.PipelineResponse\"\x00\x12N\n\rRegisterAgent\x12\x1c.protos.RegisterAgentRequest\x1a\x1d.protos.RegisterAgentResponse\"\x00\x12R\n\x0f\x43lientHeartBeat\x12\x1d.protos.AgentHeartBeatRequest\x1a\x1e.protos.AgentHeartBeatResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,models__pb2.DESCRIPTOR,])




_PIPELINEREQUEST = _descriptor.Descriptor(
  name='PipelineRequest',
  full_name='protos.PipelineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protos.PipelineRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='protos.PipelineRequest.creation_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=151,
)


_PIPELINERESPONSE = _descriptor.Descriptor(
  name='PipelineResponse',
  full_name='protos.PipelineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=171,
)


_REGISTERAGENTREQUEST = _descriptor.Descriptor(
  name='RegisterAgentRequest',
  full_name='protos.RegisterAgentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_info', full_name='protos.RegisterAgentRequest.system_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=236,
)


_REGISTERAGENTRESPONSE = _descriptor.Descriptor(
  name='RegisterAgentResponse',
  full_name='protos.RegisterAgentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='protos.RegisterAgentResponse.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=280,
)


_AGENTHEARTBEATREQUEST = _descriptor.Descriptor(
  name='AgentHeartBeatRequest',
  full_name='protos.AgentHeartBeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='protos.AgentHeartBeatRequest.unique_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid_count', full_name='protos.AgentHeartBeatRequest.pid_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_memory_used', full_name='protos.AgentHeartBeatRequest.percent_memory_used', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=372,
)


_AGENTHEARTBEATRESPONSE = _descriptor.Descriptor(
  name='AgentHeartBeatResponse',
  full_name='protos.AgentHeartBeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=398,
)

_PIPELINEREQUEST.fields_by_name['creation_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REGISTERAGENTREQUEST.fields_by_name['system_info'].message_type = models__pb2._SYSTEMINFO
DESCRIPTOR.message_types_by_name['PipelineRequest'] = _PIPELINEREQUEST
DESCRIPTOR.message_types_by_name['PipelineResponse'] = _PIPELINERESPONSE
DESCRIPTOR.message_types_by_name['RegisterAgentRequest'] = _REGISTERAGENTREQUEST
DESCRIPTOR.message_types_by_name['RegisterAgentResponse'] = _REGISTERAGENTRESPONSE
DESCRIPTOR.message_types_by_name['AgentHeartBeatRequest'] = _AGENTHEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['AgentHeartBeatResponse'] = _AGENTHEARTBEATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PipelineRequest = _reflection.GeneratedProtocolMessageType('PipelineRequest', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINEREQUEST,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.PipelineRequest)
  ))
_sym_db.RegisterMessage(PipelineRequest)

PipelineResponse = _reflection.GeneratedProtocolMessageType('PipelineResponse', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINERESPONSE,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.PipelineResponse)
  ))
_sym_db.RegisterMessage(PipelineResponse)

RegisterAgentRequest = _reflection.GeneratedProtocolMessageType('RegisterAgentRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERAGENTREQUEST,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.RegisterAgentRequest)
  ))
_sym_db.RegisterMessage(RegisterAgentRequest)

RegisterAgentResponse = _reflection.GeneratedProtocolMessageType('RegisterAgentResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERAGENTRESPONSE,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.RegisterAgentResponse)
  ))
_sym_db.RegisterMessage(RegisterAgentResponse)

AgentHeartBeatRequest = _reflection.GeneratedProtocolMessageType('AgentHeartBeatRequest', (_message.Message,), dict(
  DESCRIPTOR = _AGENTHEARTBEATREQUEST,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.AgentHeartBeatRequest)
  ))
_sym_db.RegisterMessage(AgentHeartBeatRequest)

AgentHeartBeatResponse = _reflection.GeneratedProtocolMessageType('AgentHeartBeatResponse', (_message.Message,), dict(
  DESCRIPTOR = _AGENTHEARTBEATRESPONSE,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.AgentHeartBeatResponse)
  ))
_sym_db.RegisterMessage(AgentHeartBeatResponse)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='protos.Master',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=401,
  serialized_end=645,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecutePipeline',
    full_name='protos.Master.ExecutePipeline',
    index=0,
    containing_service=None,
    input_type=_PIPELINEREQUEST,
    output_type=_PIPELINERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterAgent',
    full_name='protos.Master.RegisterAgent',
    index=1,
    containing_service=None,
    input_type=_REGISTERAGENTREQUEST,
    output_type=_REGISTERAGENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClientHeartBeat',
    full_name='protos.Master.ClientHeartBeat',
    index=2,
    containing_service=None,
    input_type=_AGENTHEARTBEATREQUEST,
    output_type=_AGENTHEARTBEATRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER

# @@protoc_insertion_point(module_scope)
