# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmaster.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n\x0fPipelineRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x31\n\rcreation_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x12\n\x10PipelineResponse2P\n\x06Master\x12\x46\n\x0f\x45xecutePipeline\x12\x17.protos.PipelineRequest\x1a\x18.protos.PipelineResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PIPELINEREQUEST = _descriptor.Descriptor(
  name='PipelineRequest',
  full_name='protos.PipelineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protos.PipelineRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='protos.PipelineRequest.creation_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=137,
)


_PIPELINERESPONSE = _descriptor.Descriptor(
  name='PipelineResponse',
  full_name='protos.PipelineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=157,
)

_PIPELINEREQUEST.fields_by_name['creation_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PipelineRequest'] = _PIPELINEREQUEST
DESCRIPTOR.message_types_by_name['PipelineResponse'] = _PIPELINERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PipelineRequest = _reflection.GeneratedProtocolMessageType('PipelineRequest', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINEREQUEST,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.PipelineRequest)
  ))
_sym_db.RegisterMessage(PipelineRequest)

PipelineResponse = _reflection.GeneratedProtocolMessageType('PipelineResponse', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINERESPONSE,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:protos.PipelineResponse)
  ))
_sym_db.RegisterMessage(PipelineResponse)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='protos.Master',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=159,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecutePipeline',
    full_name='protos.Master.ExecutePipeline',
    index=0,
    containing_service=None,
    input_type=_PIPELINEREQUEST,
    output_type=_PIPELINERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER

# @@protoc_insertion_point(module_scope)
